"""empty message

Revision ID: 05c3a7da4ea8
Revises: 400849841331
Create Date: 2019-03-19 08:56:07.818872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05c3a7da4ea8'
down_revision = '400849841331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Company', sa.Column('email', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Company', 'email')
    # ### end Alembic commands ###
