"""empty message

Revision ID: 400849841331
Revises: 5087374c3ee4
Create Date: 2019-03-19 07:57:16.154577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '400849841331'
down_revision = '5087374c3ee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position', sa.Column('place', sa.String(), nullable=True))
    op.add_column('position', sa.Column('time', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('position', 'time')
    op.drop_column('position', 'place')
    # ### end Alembic commands ###
