"""empty message

Revision ID: 43df9edc1645
Revises: b7693f626fea
Create Date: 2019-03-13 09:00:24.245518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43df9edc1645'
down_revision = 'b7693f626fea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Company', sa.Column('contacts', sa.String(length=32768), nullable=True))
    op.add_column('Company', sa.Column('website', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Company', 'website')
    op.drop_column('Company', 'contacts')
    # ### end Alembic commands ###
