"""empty message

Revision ID: 45a7803d219f
Revises: ff309e7e5371
Create Date: 2019-04-11 01:53:47.224637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45a7803d219f'
down_revision = 'ff309e7e5371'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Application', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Application', 'User', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Application', type_='foreignkey')
    op.drop_column('Application', 'user_id')
    # ### end Alembic commands ###
