"""empty message

Revision ID: 5087374c3ee4
Revises: 43df9edc1645
Create Date: 2019-03-14 08:53:51.405118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5087374c3ee4'
down_revision = '43df9edc1645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position', sa.Column('available', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('position', 'available')
    # ### end Alembic commands ###
