"""empty message

Revision ID: 57a658eaccea
Revises: 723f345cb54d
Create Date: 2019-06-19 16:41:44.939626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57a658eaccea'
down_revision = '723f345cb54d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Verify', type_='foreignkey')
    op.drop_column('Verify', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Verify', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'Verify', 'User', ['user_id'], ['id'])
    # ### end Alembic commands ###
