"""remove unique flag

Revision ID: 6046a1445a3f
Revises: ff0f5f683228
Create Date: 2018-12-30 06:14:46.358088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6046a1445a3f'
down_revision = 'ff0f5f683228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_position_name', table_name='position')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_position_name', 'position', ['name'], unique=1)
    # ### end Alembic commands ###
