"""empty message

Revision ID: 8e565d56f02c
Revises: 86c6b8113c09
Create Date: 2019-04-02 11:30:01.237150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e565d56f02c'
down_revision = '86c6b8113c09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Application', sa.Column('company_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Application', 'company_id')
    # ### end Alembic commands ###
