"""empty message

Revision ID: c98343d39ed1
Revises: 59d9c850997b
Create Date: 2018-12-29 06:38:47.785903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c98343d39ed1'
down_revision = '59d9c850997b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Company', sa.Column('logo', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Company', 'logo')
    # ### end Alembic commands ###
