"""empty message

Revision ID: cea18f2c1990
Revises: 57533bf62685
Create Date: 2019-02-19 08:46:13.428517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cea18f2c1990'
down_revision = '57533bf62685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('type_registration', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'type_registration')
    # ### end Alembic commands ###
