"""add position table

Revision ID: ff0f5f683228
Revises: c98343d39ed1
Create Date: 2018-12-30 05:19:19.825368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff0f5f683228'
down_revision = 'c98343d39ed1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('requirements', sa.String(length=32768), nullable=True),
    sa.Column('optional_skills', sa.String(length=32768), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['Company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_position_name'), 'position', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_position_name'), table_name='position')
    op.drop_table('position')
    # ### end Alembic commands ###
