name: Notifier

on: [push, pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - name: Install requests
      run: |
        pip install requests
    - name: Sent notification
      run: |
        import requests
        import json
        def send_request():
            try:
                response = requests.post(
                    url="https://push.techulus.com/api/v1/notify/bbcf1444-9d53-4cf4-8303-67cd8be38065",
                    headers={
                        "Content-Type": "application/json; charset=utf-8",
                    },
                    data=json.dumps({
                        "title": "Push by Techulus",
                        "body": "This is your first push notification"
                    })
                )
                print('Response HTTP Status Code: {status_code}'.format(
                    status_code=response.status_code))
                print('Response HTTP Response Body: {content}'.format(
                    content=response.content))
            except requests.exceptions.RequestException:
                print('HTTP Request failed')
        shell: python
